### ISSUE TITLE
Mix ecto.migrate doesn’t finish in terminal 

### ISSUE THREAD

**Issue by shahryarjb** [elixir-ecto/ecto#2845]
### Precheck

Hello, `mix ecto.migrate` doesn’t finish when I run it, but it works until first migration and I’m forced to push CTRL + C to stop this, please see my pic:

![Mix ecto.migrate doesn’t finish in terminal ](https://elixirforum.com/uploads/default/original/2X/a/aaddd866332e6a9d11877b5bd941a3ee1d4eab05.png)

it doesn’t go to next migration

### Environment

* Elixir version (elixir -v): v1.7.4
* postgres (PostgreSQL) 10.1
* Ecto version (mix deps):
* `{:phoenix_ecto, "~> 4.0"}  {:ecto_sql, "~> 3.0"},  {:postgrex, ">= 0.0.0"} `
* Operating system: mac os last version

**Comment by josevalim** [comment]
Thanks @shahryarjb! Do you have a way we can reproduce this issue? Maybe a small repo we could clone and run `mix ecto.migrate` on? Thank you.

**Comment by Eiji7** [comment]
I can reproduce it also on `PostgreSQL` in version `11.1`.

**Comment by shahryarjb** [comment]
@Eiji7 I have tested it on PostgreSQL 11.1, but it doesn't work 
https://elixirforum.com/t/mix-ecto-migrate-doesnt-finish-in-terminal/18313

**Comment by josevalim** [comment]
It seems to be an issue with our new transaction lock. It is the same issue as seen here #2703.

What happens if you set `migration_lock: nil` in your repo configuration here? https://github.com/shahryarjb/weeding_cards/blob/master/config/dev.exs#L70 Does it help?

**Comment by shahryarjb** [comment]
Hello, if you mean somethings like this 
![screenshot 2018-11-29 at 9 40 40 pm](https://user-images.githubusercontent.com/8413604/49242228-822dc000-f41f-11e8-9216-ad521a892406.png)

it didn't work, it was stoped and didn't continue to migrate all migration

**Comment by josevalim** [comment]
Noted. Can you please try ecto_sql master? I have pushed a fix.

**Comment by fmcgeough** [comment]
@josevalim I had reproduced this. 

I tried it with ecto_sql master 
and with migration_lock: nil it finishes. Without  migration_lock: nil on the Repo it still hangs.

**Comment by josevalim** [comment]
Thanks, new version is out!
